### ISSUE TITLE
setOnDim and brightness card

### ISSUE THREAD

**Issue by goyaweb** [caseda/com.tkbhome#18]
please add setOnDim capabilityoption and add a set brightness card. Similar to the fibaro app:
https://github.com/athombv/com.fibaro/pull/106/files

**Comment by caseda** [comment]
I will add the tag when I am ready with the thing I am working on now.

What do you mean with set brightness card, all devices with a dim capability already have a dim card, the one in the PR is pure for a parameter change that the fibaro has, I believe tkb has no force dim level when turning on parameter

**Comment by caseda** [comment]
i've added the capabilitiesOption

i did not add such a flow card, since that is not possible in this device.

if you disagree, and can show me it is possible then please re-open it

(PS: it is not possible with internal settings, that is not looked at when being triggered from outside sources like direct associations of other switches)
