### ISSUE TITLE
Switch behaviour text switched

### ISSUE THREAD

**Issue by goyaweb** [caseda/com.tkbhome#2]
When selecting: "switch up = on, switch down = off" it does exactly the opposite.

**Comment by caseda** [comment]
Then you have your switch upside down? exactly like the parameter is for, so you can put it upside down.

but since you are the second one that mentions it i will see if the Manual is wrong with my own device, or people just don't know how to install devices :D and update the parameter description to be more clear.

i still need to fix the entire driver for them anyway, since (like the README states) Switch doesn't work properly yet ;)

> 1*:
> The TZ65(D) doesn't work properly yet (only right switch (TZ65D) work with "on & off"). Expect it to fully work in the next update (0.9.5), very soon.

even though it's not very soon anymore

**Comment by goyaweb** [comment]
i've installed the unit in the same way as the product picture you used (leds bottom).
What do you mean by "only right switch work with "on & off". In my experience right switch doesn't work at all, only the left switch works.

**Comment by caseda** [comment]
Yup it's my mistake in the description/options, will fix it when i update the driver as well.
will work on it this evening (probably) but will definitely work within this week.
will be most likely without "Hold" options, can't think of a reliable way to recognize this yet.
unless the next homey update also fixes the signal not coming in i was expecting.

**Comment by caseda** [comment]
changed the description in latest update, and should make it more clear now :+1: thanks for reporting
