### ISSUE TITLE
TSM02 - motion alarm

### ISSUE THREAD

**Issue by Drops70** [caseda/com.tkbhome#28]
Sorry to bother again ....
I have one 4-1 sensor (TSM02) and the motion alarm is always on.
Already tried to Chance the Settings, exclude and include again.
But once the Motion Alarm is triggered is stays on for ever.

Any Idea on this?

**Comment by caseda** [comment]
Hmm, I don't have this device type myself, so without any logging pretty I much impossible to help on this one.

Can you send in some logging?
Or look your self if you see something that looks like an off command.

**Comment by caseda** [comment]
Oh BTW, can remember something that it didn't send the motion off command without association group 2, can you confirm homeys id is in there?

**Comment by Drops70** [comment]
Group 2 was empty. Changed to 1 and will see if this works. I will report on this.

**Comment by Drops70** [comment]
Unfortunately no success still motion alarm on all the time.
Will exclude the device as it is draining the battery and is not working well.

**Comment by caseda** [comment]
if the battery is draining, then that means it keeps sending data (motion on probably) to homey,
so that makes it not an app issue, but a device issue, there for closing this issue.

if you disagree please enclose the log files of any data to and from this device, then i might be able help you further, and re-open if it is does look like an app issue, but for now, it really doesn't look like it.
