### ISSUE TITLE
TZ56D flow not work

### ISSUE THREAD

**Issue by vlasinus** [caseda/com.tkbhome#31]
T56D detect as T36/T56 and flow not work.
work only "right 2x on/off" and then it works when you press it once

**Comment by caseda** [comment]
For the naming with the "missing" D is because the single and double switches have the same id's, impossible to see the difference by the app.

The other issue is the same issue as #27
Some devices seem to work differently then they are supposed to/did before.

I have not found a way to determine in which way it works, and might not be able to fix it completely without having a device that works differently myself.

I will close this issue for now, and will keep you posted in #27 if I find a way to fix this issue.
