### ISSUE TITLE
why v2.02 is not in Homey APPs, because I found that v2.02 already supports TZ74, but V2.01 in Homey APPs does not support this?

### ISSUE THREAD

**Issue by sh1536** [caseda/com.tkbhome#46]
Hi, may I ask why v2.02 is not in Homey APPs, because I found that v2.02 already supports TZ74, but V2.01 in Homey APPs does not support this?

Not from a country that speaks English, there may be spelling mistakes, please forgive, thanks.

_Originally posted by @sh1536 in https://github.com/caseda/com.tkbhome/issues/44#issuecomment-451330701_

**Comment by caseda** [comment]
As mentioned in #39, #43 and #44, I could not update the app because the validator athom used made it impossible to update the app without a lot of breaking existing device installs.

Have been waiting for a fix by athom since Aug 9th (and was only finally fixed yesterday)
When I'm updating still is another question, as there are still several issues that need to be fixed, and I only have limited spare time that I can and _want_ to invest in this app.

**Comment by sh1536** [comment]
Thank you for your reply, I have all the TKBHOME products here, I can give you as much help as possible.
